### ISSUE TITLE
Roadmap: Version 2.0

### ISSUE THREAD

**Issue by b0g3r** [b0g3r/perseus#7]
- [ ] perseus doesn't have any code from snapshottest
 - [ ] perseus has an easily extendable way to work with different data: complex structures, trees, images (thoughts in #2)
 - [ ] perseus has awesome logo (#3)
 - [ ] totally removed `assert_match()` syntax
